# Based on https://github.com/withastro/astro/blob/main/.devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/javascript-node:22

# Install latest yarn
RUN npm install -g yarn

COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt